/**
 * Central site configuration — single source of truth for SEO / metadata.
 * Override the URL per-environment with NEXT_PUBLIC_SITE_URL (e.g. on Vercel).
 */
export const SITE = {
  name: 'GlofiHub',
  legalName: 'GlofiHub Private Limited',
  url: (process.env.NEXT_PUBLIC_SITE_URL || 'https://glofihub.com').replace(/\/$/, ''),
  title: 'GlofiHub — Education, Counselling, Academy, Import-Export & Technology',
  shortTitle: 'GlofiHub',
  description:
    'GlofiHub is an ecosystem connecting learners, professionals, institutions and businesses with education (study abroad, MBBS abroad & admissions in India), counselling, skills training, careers, consulting, technology, import-export and global opportunities. Trusted by students across India, Russia & Central Asia.',
  tagline: 'A Gateway to Infinite Possibilities',
  locale: 'en_IN',
  email: 'info@glofihub.com',
  phone: '+919241168875',
  phoneDisplay: '+91 924 116 8875',
  whatsapp: '919241168875',
  ogImage: '/logo/logo.png',
  keywords: [
    'study abroad consultants',
    'MBBS abroad',
    'MBBS in Russia',
    'overseas education',
    'education consultancy India',
    'study abroad India',
    'career guidance',
    'job placement',
    'skill development',
    'education in India',
    'admission counselling',
    'student visa assistance',
    'GlofiHub',
    // Ecosystem-level terms
    'GlofiHub ecosystem',
    'GlofiHub Education',
    'GlofiHub Counselling',
    'GlofiHub Academy',
    'GlofiHub Import-Export',
    'GlofiHub Consulting',
    'GlofiHub Technology',
    'GlofiHub Partner Network',
    'jobs and careers',
    'global opportunities',
    'international scholarships',
    'skill training',
    'career-ready courses',
    'web development',
    'app development',
    'AI agents',
    'digital marketing',
    'partner network',
  ],
  social: {
    instagram: 'https://www.instagram.com/glofihub',
    facebook: 'https://www.facebook.com/glofihub',
    youtube: 'https://www.youtube.com/@glofihub',
    linkedin: 'https://www.linkedin.com/company/glofihub',
  },
} as const;
