/**
 * Central site configuration — single source of truth for SEO / metadata.
 * Override the URL per-environment with NEXT_PUBLIC_SITE_URL (e.g. on Vercel).
 */
export const SITE = {
  name: 'GlofiHub',
  legalName: 'GlofiHub',
  url: (process.env.NEXT_PUBLIC_SITE_URL || 'https://glofihub.com').replace(/\/$/, ''),
  title: 'GlofiHub — Study Abroad, MBBS, Academy, Export–Import & Digital',
  shortTitle: 'GlofiHub',
  description:
    'GlofiHub is a group of businesses — GlofiHub Education (study abroad, MBBS abroad & admissions in India), GlofiHub Digital (web, apps, AI & marketing), with GlofiHub Academy skill training and Export–Import services launching soon. Trusted by students across India, Russia & Central Asia.',
  tagline: 'Gateway to Infinite Possibilities',
  locale: 'en_IN',
  email: 'info@glofihub.com',
  phone: '+919241168875',
  phoneDisplay: '+91 924 116 8875',
  whatsapp: '919241168875',
  ogImage: '/logo/logo.png',
  keywords: [
    'study abroad consultants',
    'MBBS abroad',
    'MBBS in Russia',
    'overseas education',
    'education consultancy India',
    'study abroad India',
    'career guidance',
    'job placement',
    'skill development',
    'education in India',
    'admission counselling',
    'student visa assistance',
    'GlofiHub',
    // Group-level terms
    'GlofiHub group',
    'GlofiHub Education',
    'GlofiHub Academy',
    'GlofiHub Digital',
    'skill training',
    'career-ready courses',
    'export import services',
    'global trade support',
    'web development',
    'app development',
    'AI agents',
    'digital marketing',
    'branding and PR',
  ],
  social: {
    instagram: 'https://www.instagram.com/glofihub',
    facebook: 'https://www.facebook.com/glofihub',
    youtube: 'https://www.youtube.com/@glofihub',
    linkedin: 'https://www.linkedin.com/company/glofihub',
  },
} as const;
